services:
  # Backend Laravel
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: app_backend
    restart: unless-stopped
    working_dir: /var/www
    environment:
      QUEUE_CONNECTION: database
    volumes:
      - ./:/var/www
    networks:
      - app_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: app_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app_network

  # PostgreSQL Service
  db:
    image: postgres:15-alpine
    container_name: app_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dbdata: 